### PR TITLE
Dependecy upgrade

### PR DESCRIPTION
**Pull request by pablo384**

### CODE REVIEW

**Comment by Uuttssaavv** [comment]
Thank you for your contribution @pablo384 
Since this is just the demonstration of the architectural pattern so macOS platform is not necessary for it.

**Comment by pablo384** [comment]
I understand, I just removed the macos folder.

**Comment by Uuttssaavv** [comment]
The pipeline is failing.
Please update the flutter and dart version

**Comment by pablo384** [comment]
Now should work.

**Comment by Uuttssaavv** [comment]
Before committing your changes try to run all the workflow commands and ensure everything is working fine

**Comment by pablo384** [comment]
I think the line
dart format

Is not the right command, is deprecated.

Should be $flutter format
In the workflow file.

**Comment by pablo384** [comment]
Great, now is working as expected.

**Review by Uuttssaavv — APPROVED** [review]

**Pull request merged**
